env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - typescript
rules: {
  linebreak-style: 0
}

settings:
  react:
    version: detect
