#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[ ! -d "/dist" ] && rm -rf ./dist/
npm run build
cd dist
cp index.html 404.html
git init
git status
# 記得改git
git remote add gh-pages https://github.com/XYZ-studio/TWPTOT.git
git checkout -b gh-pages
git add --all
git commit -m "build"
git push --set-upstream gh-pages gh-pages -f
cd ..
rm -r dist